<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="AetherArk\AetherArk.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>AetherSpace.Game</StartupObject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
